import type { Metadata } from 'next'
import './globals.css'
import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'
import QueryProvider from '../components/TanStackProvider/TanStackProvider'

export const metadata: Metadata = {
  title: 'NoteHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryProvider>
          <Header />
          {children}
          {modal}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  )
}
