import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import QueryProvider from './components/TanStackProvider/TanStackProvider'

export const metadata: Metadata = {
  title: 'NoteHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <QueryProvider>{children}</QueryProvider>
        <Footer />
      </body>
    </html>
  )
}
